### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by ppusapati** [gioboa/qwik-microfrontend-starter#3]
Rendered page normally but on click events are not triggering in both host and remote applications

on click of Host:
```
(index):1257 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at dispatch ((index):1257:33)
    at HTMLDocument.processDocumentEvent ((index):1332:33) 
```

onclick on remote counter:

```
Failed to fetch dynamically imported module: http://localhost:4173/remote//%40fs/C%3A%5CUsers%5Cppusa%5CDownloads%5Cmicrofrontend%20qwikjs%5Cqwik-microfrontend-starter-main%5Cremote%5Csrc%5Ccomponents/counter_component_button_onclick_cwtykrjfdae.js?_qrl_parent=C%3ADownloads%5Cmicrofrontend%20qwikjs%5Cqwik-microfrontend-starter-main%5Cremote%5Csrc%5Ccomponents%5CCounter.tsx
```

is this a working example?

**Comment by gioboa** [comment]
Hi, to solve that problem you need to update Qwik and Qwik City
If I remember correctly, 1.6.0 was a the orrible release with few regressions

**Comment by ppusapati** [comment]
Thank you. Have upgraded both to Qwik and Qwik City to 1.6.0 and its working. 

now if I have multiple routes in remote application. How to handle them in host?

**Comment by gioboa** [comment]
Can you give me a practical example?

**Comment by ppusapati** [comment]
Will revisit with a sample code. Until then will close this. Thank you

**Comment by gioboa** [comment]
You're welcome 😉

**Comment by ppusapati** [comment]
I'm experiencing two major issues with routing:

**1. Admin Application Navigation:**
   - Error: `Internal assert, this is likely caused by a bug in Qwik: out of bounds inflate access`

**2. Navigation Between MFEs (via Navbar):**
   - Error: `Missing Qwik City Env Data for help visit`

**Steps to Reproduce:**
1. Clone the repository: [qwikjs-microfrontend](https://github.com/ppusapati/qwikjs-microfrontend)
2. Navigate within the admin application.
3. Attempt to switch between MFEs using the navbar links.

Any guidance would be appreciated!

**Comment by gioboa** [comment]
@ppusapati if you want to switch MFE you need to use the full URL e.g `http://localhost:5174/` for the Admin one
